# Hexo é…ç½®æ–‡ä»¶
## æ–‡ä»¶: https://hexo.io/docs/configuration.html
## åŸå§‹ç¢¼: https://github.com/hexojs/hexo/

# ç«™é»è¨­ç½®
title: StackPenguin
description: ""
keywords:
author: StackPenguin
language: zh-TW
timezone: ""

nav:
  # logo: /images/Logo.png # é€™è£¡å¡«å…¥ä½ çš„ logo åœ–ç‰‡éˆæ¥
  display_title: true # æ˜¯å¦é¡¯ç¤ºç¶²ç«™æ¨™é¡Œ
  fixed: false # å°èˆªæ¬„æ˜¯å¦å›ºå®šåœ¨é é¢é ‚éƒ¨ï¼Œè¨­ç‚º true å‰‡å›ºå®š

menu:
  é¦–é : / || fas fa-home
  æ™‚é–“è»¸: /archives/ || fas fa-archive
  æ¨™ç±¤: /tags/ || fas fa-tags
  åˆ†é¡: /categories/ || fas fa-folder-open
  # æ¸…å–®||fa fa-heartbeat:
  #   éŸ³æ¨‚: /music/ || fas fa-music
  #   ç…§ç‰‡: /Gallery/ || fas fa-images
  #   é›»å½±: /movies/ || fas fa-video
  # å‹éˆ: /link/ || fas fa-link
  # é—œæ–¼: /about/ || fas fa-heart

# ç¶²å€è¨­ç½®
## åœ¨é€™è£¡è¨­ç½®ä½ çš„ç¶²ç«™ URLã€‚ä¾‹å¦‚ï¼Œå¦‚æœä½ ä½¿ç”¨ GitHub Pagesï¼Œå‰‡è¨­ç½® url ç‚º 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # è¨­ç½®ç‚º false å°‡å¾æ°¸ä¹…é€£çµä¸­ç§»é™¤ 'index.html'
  trailing_html: true # è¨­ç½®ç‚º false å°‡å¾æ°¸ä¹…é€£çµä¸­ç§»é™¤ '.html'

# ç›®éŒ„è¨­ç½®
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# æ’°å¯«è¨­ç½®
new_post_name: :title.md # æ–°æ–‡ç« çš„æ–‡ä»¶å
default_layout: post
titlecase: false # å°‡æ¨™é¡Œè½‰æ›ç‚ºæ¨™é¡Œå¤§å°å¯«
external_link:
  enable: true # å°‡å¤–éƒ¨éˆæ¥åœ¨æ–°æ¨™ç±¤ä¸­æ‰“é–‹
  field: site # æ‡‰ç”¨æ–¼æ•´å€‹ç¶²ç«™
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
  highlight_copy: true # é¡¯ç¤ºä»£ç¢¼æ¡†è¤‡è£½æŒ‰éˆ•
  highlight_shrink: true # ä»£ç¢¼æ¡†ä¸å±•é–‹ï¼Œéœ€é»æ“Š '>' æ‰“é–‹
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# é¦–é è¨­ç½®
# path: éƒ¨è½æ ¼é¦–é çš„æ ¹è·¯å¾‘ (é»˜èªç‚º '')
# per_page: æ¯é é¡¯ç¤ºçš„æ–‡ç« æ•¸ (0 = é—œé–‰åˆ†é )
# order_by: æ–‡ç« æ’åº (é»˜èªæŒ‰æ—¥æœŸé™åºæ’åˆ—)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# åˆ†é¡èˆ‡æ¨™ç±¤
default_category: uncategorized
category_map:
tag_map:

# ç¶²ç«™å…ƒæ•¸æ“š
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# æ—¥æœŸèˆ‡æ™‚é–“æ ¼å¼
## Hexo ä½¿ç”¨ Moment.js ä¾†è§£æå’Œé¡¯ç¤ºæ—¥æœŸ
## å¯ä»¥è‡ªå®šç¾©æ—¥æœŸæ ¼å¼ï¼Œè«‹åƒè€ƒ http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option æ”¯æŒ 'mtime', 'date', 'empty'
updated_option: "mtime"

# åˆ†é è¨­ç½®
## è¨­ç½® per_page ç‚º 0 ä»¥ç¦ç”¨åˆ†é 
per_page: 10
pagination_dir: page

# åŒ…å« / æ’é™¤æ–‡ä»¶
## include:/exclude: é¸é …åƒ…é©ç”¨æ–¼ 'source/' è³‡æ–™å¤¾
include:
exclude:
ignore:

# æ“´å±•åŠŸèƒ½
## æ’ä»¶: https://hexo.io/plugins/
## ä¸»é¡Œ: https://hexo.io/themes/
theme: butterfly

# å®¢è£½åŒ–å…§å®¹
footer:
  owner:
    enable: true
    since: 2024
  custom_text: StackPenguin | STUST
  copyright:
    enable: false
    version: false

post_pagination:
  enable: true
  newer_text: "Â« ä¸Šä¸€ç¯‡"
  older_text: "ä¸‹ä¸€ç¯‡ Â»"

related_post:
  enable: true
  limit: 6 # é¡¯ç¤ºæ¨è–¦æ–‡ç« æ•¸ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸé¡¯ç¤ºå‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

toc:
  post: true
  page: true
  number: true
  expand: false
  style_simple: false # for post
  scroll_percent: true

copy:
  enable: true

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

post_meta:
  page:
    date_type: both # created or updated or both ä¸»é æ–‡ç« æ—¥æœŸæ˜¯å‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½é¡¯ç¤º
    date_format: relative # date/relative é¡¯ç¤ºæ—¥æœŸé‚„æ˜¯ç›¸å°æ—¥æœŸ
    categories: true # true or false ä¸»é æ˜¯å¦é¡¯ç¤ºåˆ†é¡
    tags: true # true or false ä¸»é æ˜¯å¦é¡¯ç¤ºæ¨™ç±¤
    label: true # true or false é¡¯ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: both # created or updated or both æ–‡ç« é æ—¥æœŸæ˜¯å‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½é¡¯ç¤º
    date_format: relative # date/relative é¡¯ç¤ºæ—¥æœŸé‚„æ˜¯ç›¸å°æ—¥æœŸ
    categories: true # true or false æ–‡ç« é æ˜¯å¦é¡¯ç¤ºåˆ†é¡
    tags: true # true or false æ–‡ç« é æ˜¯å¦é¡¯ç¤ºæ¨™ç±¤
    label: true # true or false é¡¯ç¤ºæè¿°æ€§æ–‡å­—

index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

# disable_top_img: false

error_404:
  enable: true
  subtitle: "é é¢æ²’æœ‰æ‰¾åˆ°"

social:
  fab fa-instagram: https://www.instagram.com/zhuang_2024/ || Instagram || "#E4405F"
  fab fa-line: https://line.me/ti/p/EeWpQ7ef-e || LINE || "#00C300"
  fab fa-facebook: https://www.facebook.com/profile.php?id=100002212333597 || Facebook || "#4267B2"

avatar:
  img: /images/Avatar.jpeg
  effect: false

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both

aside:
  enable: true
  hide: false
  button: true
  mobile: true # æ‰‹æ©Ÿç‰ˆé¡¯ç¤º
  position: right # å·¦é‚Šæˆ–å³é‚Š
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/KingKaiZhuang

  card_announcement:
    enable: true
    content: |
      <p>ğŸ« STUST</p>
      <p>ğŸ“– æ­£åœ¨æº–å‚™ <strong>CPE</strong> å’Œ <strong>å¤šç›Š</strong>ã€‚</p>

  card_recent_post:
    enable: true
    limit: 5 # è¨­ç½®ç‚º 0 å°‡é¡¯ç¤ºæ‰€æœ‰
    sort: date # æŒ‰æ—¥æœŸæˆ–æ›´æ–°æ—¥æœŸæ’åº
    sort_order: # ä¸è¦ä¿®æ”¹æ­¤è¨­ç½®ï¼Œé™¤éä½ çŸ¥é“å®ƒçš„ä½œç”¨
  card_categories:
    enable: true
    limit: 8 # è¨­ç½®ç‚º 0 å°‡é¡¯ç¤ºæ‰€æœ‰
    expand: none # none/true/false
    sort_order: # ä¸è¦ä¿®æ”¹æ­¤è¨­ç½®ï¼Œé™¤éä½ çŸ¥é“å®ƒçš„ä½œç”¨
  card_tags:
    enable: true
    limit: 40 # è¨­ç½®ç‚º 0 å°‡é¡¯ç¤ºæ‰€æœ‰
    color: false
    orderby: random # æ¨™ç±¤é †åºï¼Œrandom/name/length
    order: 1 # æ’åºã€‚1 ç‚ºå‡åºï¼Œ-1 ç‚ºé™åº
    sort_order: # ä¸è¦ä¿®æ”¹æ­¤è¨­ç½®ï¼Œé™¤éä½ çŸ¥é“å®ƒçš„ä½œç”¨
  card_archives:
    enable: true
    type: monthly # yearly æˆ– monthly
    format: MMMM YYYY # ä¾‹å¦‚: YYYYå¹´MMæœˆ
    order: -1 # æ’åºã€‚1 ç‚ºå‡åºï¼Œ-1 ç‚ºé™åº
    limit: 8 # è¨­ç½®ç‚º 0 å°‡é¡¯ç¤ºæ‰€æœ‰
    sort_order: # ä¸è¦ä¿®æ”¹æ­¤è¨­ç½®ï¼Œé™¤éä½ çŸ¥é“å®ƒçš„ä½œç”¨
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # ä¸è¦ä¿®æ”¹æ­¤è¨­ç½®ï¼Œé™¤éä½ çŸ¥é“å®ƒçš„ä½œç”¨
  card_post_series:
    enable: true
    orderBy: "date" # æŒ‰æ¨™é¡Œæˆ–æ—¥æœŸæ’åº
    order: -1 # æ’åºã€‚1 ç‚ºå‡åºï¼Œ-1 ç‚ºé™åº

# è¨ªå•äººæ•¸çµ±è¨ˆ
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

runtimeshow:
  enable: true
  publish_date: 11/9/2024 00:00:00
  ## ç¶²ç«™é–‹é€šæ™‚é–“
  # æ ¼å¼: æœˆ/æ—¥/å¹´ æ™‚é–“
  # ä¹Ÿå¯ä»¥å¯«æˆ å¹´/æœˆ/æ—¥ æ™‚é–“
# æ·±è‰²æ¨¡å¼
darkmode:
  enable: true
  # æ·±è‰²æ¨¡å¼èˆ‡äº®è‰²æ¨¡å¼åˆ‡æ›æŒ‰éˆ•
  button: true
  autoChangeMode: false
  # è¨­å®šäº®è‰²æ¨¡å¼æ™‚é–“ã€‚å€¼æ‡‰ä»‹æ–¼ 0 åˆ° 24 ä¹‹é–“ã€‚è‹¥æœªè¨­ç½®ï¼Œé»˜èªå€¼ç‚º 6 å’Œ 18
  start: # 8
  end: # 22

# é¡¯ç¤ºæ²å‹•ç™¾åˆ†æ¯”åœ¨è¿”å›é ‚éƒ¨æŒ‰éˆ•ä¸­
rightside_scroll_percent: true

# Aside widget - Newest Comments
newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # unit: mins, save data to localStorage
  avatar: true

# abcjs (æ¨‚è­œæ¸²æŸ“)
# See https://github.com/paulrosen/abcjs
# ---------------
abcjs:
  enable: true
  per_page: true

series:
  enable: true
  orderBy: "title" # Order by title or date
  order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
  number: true

algolia_search:
  enable: true
  hits:
    per_page: 6

# Facebook Comments Plugin
# https://developers.facebook.com/docs/plugins/comments/
facebook_comments:
  app_id:
  user_id: # optional
  pageSize: 10 # The number of comments to show
  order_by: social # social/time/reverse_time
  lang: zh_TW # Language en_US/zh_CN/zh_TW and so on

# Chat Button [recommend]
# It will create a button in the bottom right corner of website, and hide the origin button
chat_btn: true
# The origin chat button is displayed when scrolling up, and the button is hidden when scrolling down
chat_hide_show: true

top_img:
  enable: true

index_img: /images/banner.jpeg

# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: true #  open shake (æŠ–å‹•ç‰¹æ•ˆ)
  mobile: false

canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false #è¨­ç½®æ˜¯å¦æ¯æ¬¡é»æ“Šéƒ½æ›´æ›ç¶µå¸¶
  mobile: true # false æ‰‹æ©Ÿç«¯ä¸é¡¯ç¤º true æ‰‹æ©Ÿç«¯é¡¯ç¤º

fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# ç¾åŒ–é é¢é¡¯ç¤º
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

# ä¸»é subtitle
subtitle:
  enable: true
  # Typewriter Effect (æ‰“å­—æ•ˆæœ)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  # loop (å¾ªç’°æ‰“å­—)
  loop: true
  # source èª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰ https://hitokoto.cn/
  # source: 2  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰ http://yijuzhan.com/
  # source: 3  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰ https://www.jinrishici.com/
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœé—œé–‰æ‰“å­—æ•ˆæœï¼Œsubtitle åªæœƒé¡¯ç¤º sub çš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - ä¸ç›¸ä¿¡è‡ªå·±çš„äººï¼Œé€£åŠªåŠ›çš„åƒ¹å€¼éƒ½æ²’æœ‰ã€‚
    - ä¸è¦å°å¤–è¡¨éåˆ†åœ¨æ„ï¼Œå¿ƒéˆæ‰æ˜¯æœ€é‡è¦çš„ã€‚
    - å‘½é‹æ˜¯ä»»ä½•äººä¹Ÿç„¡æ³•æ”¹è®Šçš„ï¼Œä½†ä»–å¯ä»¥æ±ºå®šæ˜¯ç­‰æ­»é‚„æ˜¯é¢å°ã€‚
    - å …å¼·ä¸æ˜¯é¢å°æ‚²å‚·ä¸æµä¸€æ»´æ·šï¼Œè€Œæ˜¯æ“¦ä¹¾çœ¼æ·šå¾Œå¾®ç¬‘é¢å°ä»¥å¾Œçš„ç”Ÿæ´»ã€‚
    - æœ‰æ™‚å€™ï¼Œå …æŒäº†ä½ æœ€ä¸æƒ³å¹¹çš„äº‹æƒ…ä¹‹å¾Œï¼Œä¾¿å¯å¾—åˆ°ä½ æœ€æƒ³è¦çš„æ±è¥¿ã€‚

# åŠ è¼‰å‹•ç•« Loading Animation
preloader:
  enable: true
  source: 2 # ä½¿ç”¨ pace é€²åº¦æ¢æ•ˆæœ
  pace_css_url: https://cdn.jsdelivr.net/npm/pace-js@latest/themes/blue/pace-theme-flash.css # pace çš„ CSS æ–‡ä»¶ URL

# aplayer:
#   meting:
#   asset_inject: false
#   data-autoplay: false

# Inject the css and script (aplayer/meting)
# aplayerInject:
#   enable: true
#   per_page: true

inject:
  head:
    - <link rel="stylesheet" href="/css/wave.css">
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
    - <div class="aplayer no-destroy"  data-id="60198" data-server="netease" data-type="playlist" data-fixed="true" data-autoplay="false"> </div>

default_cover:
  - https://jsd.012700.xyz/gh/jerryc127/CDN@latest/cover/default_bg.png

# tidio
# https://www.tidio.com/
tidio:
  enable: true
  public_key: p2vvxddelwnygtsjyyuqs055bjigrdgq

infinite_scroll:
  enable: true
  distance: 50

# https://instant.page/
# prefetch (é åŠ è¼‰)
instantpage: true
